baseURL = "https://devopscompliancefwk.com/"
languageCode = "en-us"
title = "DevOps Compliance Framework"

[taxonomies]
  risk = 'risks'
  level = 'levels'

[params]
  company = 'AcmePay'
  csor = 'a compliance system of record'

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1