baseURL = "https://kosli.com/sdlctemplate"
languageCode = "en-us"
title = "DevOps Control Framework"
theme = "hugo-book"

[taxonomies]
  risk = 'risks'
  level = 'levels'

[params]
  company = 'AcmePay'
  csor = 'a compliance system of record'
  vcs = 'git'
  vcsHost = 'github'
  forkLink = 'https://github.com/kosli-dev/devopsctl/fork'
  logo = 'svg/logo.svg'
  BookSection = '/'

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3