baseURL = "https://devopscompliancefwk.com/"
languageCode = "en-us"
title = "DevOps Compliance Framework"


[params]
  company = 'AcmePay'

[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1